name: Generate Snake Contributions

on:
  schedule:
    - cron: '30 23 * * *'
    
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk/svg-only@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/gen/snake.svg?color:snake=#1688fo&color_dots=#11dddd,#ffd11a,#d61006,#bf58ff,#3dd50a
      # Commit the changes
      - name: Commit files
        run: |
          git config --local user.email "iam2kabhishek@gmail.com"
          git config --local user.name "Abhishek via github-actions"
          git add .
          git pull --rebase --autostash
          git commit -m "docs: Update Snake Contribution Animation"
      # Push the changes
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
